sudo: false
language: python
cache: pip

python:
  - "3.6"

install:
  - pip install pipenv
  - pip install codecov
  - pipenv install --dev

script:
  - pipenv run flake8 *.py
  - pipenv run pytest

after_success: codecov

